In [26]:
import pandas as pd
import numpy as np

In [36]:
import pandas as pd
print(pd.__version__)

3.0.6

In [8]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
lf = len(df)
lf
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

In [11]:
set(df["fuel_type"])

{'Diesel', 'Gasoline', 'Hybrid'}

In [12]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [13]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [15]:
max_ef = df[(df["origin"].str.lower() == "asia")].groupby("fuel_efficiency_mpg").max()
max_ef

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration
fuel_efficiency_mpg,,,,,,,,,,
21.3,1976,Asia,Gasoline,All-wheel drive,5,2670,7,NaN,4900,19.5
21.9,1977,Asia,Gasoline,Front-wheel drive,4,2590,7,276.0,4660,20.0
22.5,1980,Asia,Gasoline,Rear-wheel drive,3,2670,7,273.0,4690,17.9
22.7,1981,Asia,Gasoline,Rear-wheel drive,2,2530,7,280.0,4440,18.3
22.8,1991,Asia,Gasoline,All-wheel drive,5,2250,6,269.0,4240,16.9
...,...,...,...,...,...,...,...,...,...,...
39.0,2023,Asia,Hybrid,Rear-wheel drive,4,2100,6,228.0,3960,17.7
39.1,2021,Asia,Hybrid,Rear-wheel drive,5,1940,6,211.0,4100,19.3
39.2,2019,Asia,Hybrid,Front-wheel drive,4,2320,6,241.0,4020,19.7
39.8,2017,Asia,Hybrid,Front-wheel drive,5,2060,6,196.0,3910,19.4
41.2,2022,Asia,Diesel,Front-wheel drive,4,1990,6,225.0,3870,17.2

In [22]:
median_val = df['horsepower'].median()
most_frequent = df["horsepower"].mode()[0]
df["horsepower"] = df["horsepower"].fillna(most_frequent)
median_after = df["horsepower"].median()

print(median_val)
print(median_after)

252.0
252.0

In [35]:
asian = df[df["origin"].str.lower() == "asia"]
first_seven = asian[["vehicle_weight", "model_year"]].head(7)
X = first_seven.to_numpy()
XTX = X.T.dot(X)
XTX_inv = np.linalg.inv(XTX)

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

multiply = XTX_inv.dot(X.T).dot(y)

result = multiply.sum()
print(result)

0.36919696904925486